export enum ROLE {
  STAFF = "STAFF",
  ADMIN = "ADMIN",
  CEO = "CEO",
  BOT = "BOT",
  SECURITY = "SECURITY",
  IT = "IT",
  HR = "HR",
  ATTACHMENT = "ATTACHMENT",
}

export enum STATUS_CODE {
  // SUCCESS
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,

  // ERROR
  ERROR = -1,
  BAD_REQUEST = 400,
  INVALID_CREDENTIALS = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  PAYLOAD_TOO_LARGE = 413,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
}

export enum SYSTEM_MESSAGE {
  SYSTEM_ERROR = "Lỗi hệ thống. Vui lòng liên hệ phòng IT để được hỗ trợ!",
}

export enum ANNOUNCEMENT_TYPE {
  FEATURE_UNAVAILABLE = "FEATURE_UNAVAILABLE",
  FEATURE_IN_MAINTENANCE = "FEATURE_IN_MAINTENANCE",
}

export enum NOTIFICATION_TYPE {
  GENERAL = "GENERAL",
  POST = "POST",
  REACTION_LIKE = "REACTION_LIKE",
  REACTION_DISLIKE = "REACTION_DISLIKE",
  COMMENT = "COMMENT",
  EVENT = "EVENT",
  OTHER = "OTHER",
}
